Misc

diff --git a/.github/workflows/pr.yml b/.github/workflows/pr.yml
--- a/.github/workflows/pr.yml
+++ b/.github/workflows/pr.yml
@@ -1,20 +1,25 @@
-name: Insiders VSIX
+name: Pull Request
 
 on:
-  push:
+  pull_request:
     branches:
       - main
       - ci
+  check_run:
+    types: [rerequested, requested_action]
 
 env:
   NODE_VERSION: 12.15.0
   PYTHON_VERSION: 3.8
-  MOCHA_REPORTER_JUNIT: true
+  MOCHA_REPORTER_JUNIT: true # Use the mocha-multi-reporters and send output to both console (spec) and JUnit (mocha-junit-reporter). Also enables a reporter which exits the process running the tests if it haven't already.
   CACHE_NPM_DEPS: cache-npm
   CACHE_OUT_DIRECTORY: cache-out-directory
   CACHE_PIP_DEPS: cache-pip
+  # Key for the cache created at the end of the the 'Cache ./pythonFiles/lib/python' step.
+  CACHE_PYTHONFILES: cache-pvsc-pythonFiles
+  ARTIFACT_NAME_VSIX: ms-ai-tools-jupyter-insiders-vsix
   VSIX_NAME: ms-ai-tools-jupyter-insiders.vsix
-  VSIX_NAME_UPLOADED_TO_BLOB: ms-ai-tools-jupyter-insiders.vsix
+  COVERAGE_REPORTS: tests-coverage-reports
   CI_PYTHON_PATH: python
   TEST_RESULTS_DIRECTORY: .
 
@@ -66,7 +71,7 @@ jobs:
 
       - uses: actions/upload-artifact@v2
         with:
-          name: ${{env.VSIX_NAME}}
+          name: ${{env.ARTIFACT_NAME_VSIX}}
           path: ${{env.VSIX_NAME}}
 
   lint:
@@ -190,16 +195,20 @@ jobs:
     name: Tests (with Python)
     # The value of runs-on is the OS of the current job (specified in the strategy matrix below) instead of being hardcoded.
     runs-on: ${{ matrix.os }}
-    if: github.repository == 'microsoft/vscode-jupyter'
+    # if: github.repository == 'microsoft/vscode-jupyter'
     strategy:
       fail-fast: false
       matrix:
         # We're not running CI on macOS for now because it's one less matrix entry to lower the number of runners used,
         # macOS runners are expensive, and we assume that Ubuntu is enough to cover the UNIX case.
-        os: [ubuntu-latest, windows-latest]
-        # python: [3.6, 3.7, 3.8]
-        python: [3.8]
-        test-suite: [python-unit, single-workspace, functional]
+        os: [ubuntu-latest]
+        python: [3.8] # Use flaky tests to run against more versions of Python.
+        # python-unit: Python tests
+        # functional: Tests with mocked VS Code, & mocked Python)
+        # functional-with-jupyter: Tests with mocked VS Code & real jupyter
+        # single-workspace: Tests with VS Code
+        # integration: Tests with VS Code, Python extension & real Jupyter
+        test-suite: [python-unit, functional, test-based-on-pr-body]
     steps:
       - name: Checkout
         uses: actions/checkout@v2
@@ -287,10 +296,9 @@ jobs:
         if: startsWith(matrix.test-suite, 'functional')
         shell: bash
 
-      # debugpy  & Jedi LS is not shipped, only installed for local tests.
+      # debugpy is not shipped, only installed for local tests.
       # In production, we get debugpy & LS from python extension.
       - name: Install functional test requirements
-        #   python -m pip --disable-pip-version-check install -t ./pythonFiles/lib/python --no-cache-dir --implementation py --no-deps --upgrade -r requirements.txt
         run: |
           python -m pip --disable-pip-version-check install -r build/debugger-install-requirements.txt
           python ./pythonFiles/install_debugpy.py
@@ -298,13 +306,15 @@ jobs:
           python -m pip install --upgrade -r build/test-requirements.txt
           python -m pip install --upgrade -r ./build/ipython-test-requirements.txt
           python -m pip install --upgrade -r ./build/conda-functional-requirements.txt
+        # This step is slow.
+        # If running the placeholder suite & not required to run any tests, then don't install python dependencies.
+        if: matrix.test-suite != 'test-based-on-pr-body' || contains(github.event.pull_request.body, '[x] Run ')
 
       - name: Install dependencies (npm ci)
         run: npm ci --prefer-offline
-
-      - name: Compile if not cached
-        run: npx gulp prePublishNonBundle
-        if: steps.out-cache.outputs.cache-hit == false
+        # This step is slow.
+        # If running the placeholder suite & not required to run any tests, then don't install python dependencies.
+        if: matrix.test-suite != 'test-based-on-pr-body' || contains(github.event.pull_request.body, '[x] Run ')
 
       # Run the Python and IPython tests in our codebase.
       - name: Run Python and IPython unit tests
@@ -313,116 +323,105 @@ jobs:
           python -m IPython pythonFiles/tests/run_all.py
         if: matrix.test-suite == 'python-unit'
 
+      - name: Compile if not cached
+        run: npx gulp prePublishNonBundle
+        if: steps.out-cache.outputs.cache-hit == false
+
+      - name: Run functional tests
+        run: npm run test:functional
+        if: matrix.test-suite == 'functional'
+
       - name: Run single-workspace tests
         env:
           CI_PYTHON_VERSION: ${{matrix.python}}
         uses: GabrielBB/xvfb-action@v1.4
         with:
           run: npm run testSingleWorkspace
-        if: matrix.test-suite == 'single-workspace'
-
-      - name: Run functional tests
-        run: npm run test:functional
-        if: matrix.test-suite == 'functional'
+        if: matrix.test-suite == 'single-workspace' || (matrix.test-suite == 'test-based-on-pr-body' && github.event_name == 'pull_request' && contains(github.event.pull_request.body, '[x] Run single-workspace test'))
 
       - name: Run functional tests with Jupyter
         run: npm run test:functional
         env:
           VSCODE_PYTHON_ROLLING: 1
           VSC_PYTHON_FORCE_LOGGING: 1
-        if: matrix.test-suite == 'functional-with-jupyter'
+        if: matrix.test-suite == 'functional-with-jupyter' || (matrix.test-suite == 'test-based-on-pr-body' && github.event_name == 'pull_request' && contains(github.event.pull_request.body, '[x] Run functional-with-jupyter test'))
 
-  #   smoke-tests:
-  #     name: Smoke tests
-  #     # The value of runs-on is the OS of the current job (specified in the strategy matrix below) instead of being hardcoded.
-  #     runs-on: ${{ matrix.os }}
-  #     if: github.repository == 'microsoft/vscode-jupyter'
-  #     needs: [build-vsix]
-  #     strategy:
-  #       fail-fast: false
-  #       matrix:
-  #         # We're not running CI on macOS for now because it's one less matrix entry to lower the number of runners used,
-  #         # macOS runners are expensive, and we assume that Ubuntu is enough to cover the UNIX case.
-  #         os: [ubuntu-latest, windows-latest]
-  #         python: [3.8]
-  #     steps:
-  #       # Need the source to have the tests available.
-  #       - name: Checkout
-  #         uses: actions/checkout@v2
-
-  #       - name: Cache pip files
-  #         uses: actions/cache@v2
-  #         with:
-  #           path: ~/.cache/pip
-  #           key: ${{runner.os}}-${{env.CACHE_PIP_DEPS}}-${{env.PYTHON_VERSION}}
-
-  #       - name: Cache npm files
-  #         uses: actions/cache@v2
-  #         with:
-  #           path: ~/.npm
-  #           key: ${{runner.os}}-${{env.CACHE_NPM_DEPS}}-${{hashFiles('package-lock.json')}}
-
-  #       - name: Use Python ${{matrix.python}}
-  #         uses: actions/setup-python@v2
-  #         with:
-  #           python-version: ${{matrix.python}}
-
-  #       - name: Install dependencies (npm ci)
-  #         run: npm ci --prefer-offline
-
-  #       - name: pip install ipython requirements
-  #         run: |
-  #           python -m pip install numpy
-  #           python -m pip install --upgrade -r ./build/ipython-test-requirements.txt
-
-  #       - name: pip install jupyter
-  #         run: |
-  #           python -m pip install --upgrade jupyter
-
-  #       # Save time by reusing bits from the VSIX.
-  #       - name: Download VSIX
-  #         uses: actions/download-artifact@v2
-  #         with:
-  #           name: ${{env.VSIX_NAME}}
-
-  #       # Compile the test files.
-  #       - name: Prepare for smoke tests
-  #         run: npx tsc -p ./
-  #         shell: bash
-
-  #       - name: Set CI_PYTHON_PATH and CI_DISABLE_AUTO_SELECTION
-  #         run: |
-  #           echo "::set-env name=CI_PYTHON_PATH::python"
-  #           echo "::set-env name=CI_DISABLE_AUTO_SELECTION::1"
-  #         shell: bash
-
-  #       - name: Run smoke tests
-  #         env:
-  #           DISPLAY: 10
-  #         uses: GabrielBB/xvfb-action@v1.4
-  #         with:
-  #           run: node --no-force-async-hooks-checks ./out/test/smokeTest.js
-
-  upload:
-    name: Upload VSIX to Azure Blob Storage
-    runs-on: ubuntu-latest
-    # Extra careful to ensure this happens only in main branch.
-    # if: github.repository == 'microsoft/vscode-jupyter' && github.ref == 'refs/heads/main'
-    # needs: [tests, smoke-tests, build-vsix]
-    needs: [build-vsix, lint, ts_tests, tests]
-    env:
-      BLOB_CONTAINER_NAME: extension-builds-jupyter
-
-    steps:
-      - name: Download VSIX
-        uses: actions/download-artifact@v2
+      - name: Run DataScience tests with VSCode & Jupyter
+        uses: GabrielBB/xvfb-action@v1.4
         with:
-          name: ${{ env.VSIX_NAME }}
+          run: npm run test:testDataScience
+        env:
+          VSCODE_PYTHON_ROLLING: 1
+          VSC_PYTHON_FORCE_LOGGING: 1
+        if: matrix.test-suite == 'integration' || (matrix.test-suite == 'test-based-on-pr-body' && github.event_name == 'pull_request' && contains(github.event.pull_request.body, '[x] Run integration test'))
 
-      - name: Azure Login
-        uses: azure/login@v1.1
-        with:
-          creds: ${{ secrets.AZURE_CREDENTIALS }}
+#   smoke-tests:
+#     name: Smoke tests
+#     # The value of runs-on is the OS of the current job (specified in the strategy matrix below) instead of being hardcoded.
+#     runs-on: ${{ matrix.os }}
+#     if: github.repository == 'microsoft/vscode-jupyter'
+#     needs: [build-vsix]
+#     strategy:
+#       fail-fast: false
+#       matrix:
+#         # We're not running CI on macOS for now because it's one less matrix entry to lower the number of runners used,
+#         # macOS runners are expensive, and we assume that Ubuntu is enough to cover the UNIX case.
+#         os: [ubuntu-latest, windows-latest]
+#         python: [3.8]
+#     steps:
+#       # Need the source to have the tests available.
+#       - name: Checkout
+#         uses: actions/checkout@v2
 
-      - name: Upload to Blob Storage
-        run: az storage blob upload --file ${{ env.VSIX_NAME }} --account-name pvsc --container-name ${{ env.BLOB_CONTAINER_NAME }} --name ${{ env.VSIX_NAME_UPLOADED_TO_BLOB }}
+#       - name: Cache pip files
+#         uses: actions/cache@v2
+#         with:
+#           path: ~/.cache/pip
+#           key: ${{runner.os}}-${{env.CACHE_PIP_DEPS}}-${{env.PYTHON_VERSION}}
+
+#       - name: Cache npm files
+#         uses: actions/cache@v2
+#         with:
+#           path: ~/.npm
+#           key: ${{runner.os}}-${{env.CACHE_NPM_DEPS}}-${{hashFiles('package-lock.json')}}
+
+#       - name: Use Python ${{matrix.python}}
+#         uses: actions/setup-python@v2
+#         with:
+#           python-version: ${{matrix.python}}
+
+#       - name: Install dependencies (npm ci)
+#         run: npm ci --prefer-offline
+
+#       - name: pip install ipython requirements
+#         run: |
+#           python -m pip install numpy
+#           python -m pip install --upgrade -r ./build/ipython-test-requirements.txt
+
+#       - name: pip install jupyter
+#         run: |
+#           python -m pip install --upgrade jupyter
+
+#       # Save time by reusing bits from the VSIX.
+#       - name: Download VSIX
+#         uses: actions/download-artifact@v2
+#         with:
+#           name: ${{env.ARTIFACT_NAME_VSIX}}
+
+#       # Compile the test files.
+#       - name: Prepare for smoke tests
+#         run: npx tsc -p ./
+#         shell: bash
+
+#       - name: Set CI_PYTHON_PATH and CI_DISABLE_AUTO_SELECTION
+#         run: |
+#           echo "::set-env name=CI_PYTHON_PATH::python"
+#           echo "::set-env name=CI_DISABLE_AUTO_SELECTION::1"
+#         shell: bash
+
+#       - name: Run smoke tests
+#         env:
+#           DISPLAY: 10
+#         uses: GabrielBB/xvfb-action@v1.4
+#         with:
+#           run: node --no-force-async-hooks-checks ./out/test/smokeTest.js
